### ISSUE TITLE
Issue with last version of numba

### ISSUE THREAD

**Issue by ali-zakaria** [mavillan/py-hausdorff#12]
Hello,

With last version of numba `numba.targets` has been replaced by `numba.core`

```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    print("Hausdorff distance test: {0}".format( hausdorff_distance(X, Y, distance="manhattan") ))
  File "C:\Python37\lib\site-packages\hausdorff\hausdorff.py", line 40, in hausdorff_distance
    assert distance in _find_available_functions(distances), \
  File "C:\Python37\lib\site-packages\hausdorff\hausdorff.py", line 8, in _find_available_functions
    available_functions = [member[0] for member in all_members
  File "C:\Python37\lib\site-packages\hausdorff\hausdorff.py", line 9, in <listcomp>
    if isinstance(member[1], numba.targets.registry.CPUDispatcher)]
  File "C:\Python37\lib\site-packages\numba\__init__.py", line 140, in __getattr__
    ) from None
AttributeError: module 'numba' has no attribute 'targets'
```

**Comment by TUDelftHao** [comment]
@ali-zakaria Maybe you can find the solution here https://github.com/numba/numba/issues/5772#issuecomment-635879727

**Comment by mavillan** [comment]
Thanks for reporting @ali-zakaria
