### ISSUE TITLE
Trying to use this in clean Python and Conda leads to error

### ISSUE THREAD

**Issue by tomitrescak** [mavillan/py-hausdorff#7]
Hi, I try to use this both in regular Python and in Conda with Python 3.6 and I'm getting this error:

```
Traceback (most recent call last):
  File "/Users/tomi/Github/learning/jupyter/analysewot.py", line 17, in <module>
    t = main()
  File "/Users/tomi/Github/learning/jupyter/analysewot.py", line 13, in main
    return similarity(1600)
  File "/Users/tomi/Github/learning/jupyter/helpers/similarity.py", line 68, in similarity
    result = comp(selected_data, all_data[index])
  File "/Users/tomi/Github/learning/jupyter/helpers/compare.py", line 94, in comp
    dist = hausdorff_distance(frame[0], current[0], distance="euclidean")
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/hausdorff/hausdorff.py", line 48, in hausdorff_distance
    return _hausdorff(XA, XB, distance_function)
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 330, in _compile_for_args
    raise e
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 763, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 360, in compile_extra
    return self._compile_bytecode()
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 722, in _compile_bytecode
    return self._compile_core()
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 709, in _compile_core
    res = pm.run(self.status)
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 246, in run
    raise patched_exception
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 238, in run
    stage()
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 452, in stage_nopython_frontend
    self.locals)
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 865, in type_inference_stage
    infer.propagate()
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/typeinfer.py", line 844, in propagate
    raise errors[0]
numba.errors.TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.ArgConstraint object at 0x1128ae1d0>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/typeinfer.py", line 189, in __call__
    assert ty.is_precise()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/typeinfer.py", line 137, in propagate
    constraint(typeinfer)
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/typeinfer.py", line 190, in __call__
    typeinfer.add_type(self.dst, ty, loc=self.loc)
  File "/Users/tomi/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/Users/tomi/anaconda3/lib/python3.6/site-packages/numba/typeinfer.py", line 189, in __call__
    assert ty.is_precise()
numba.errors.InternalError: 
[1] During: typing of argument at /Users/tomi/anaconda3/lib/python3.6/site-packages/hausdorff/hausdorff.py (14)
--%<-----------------------------------------------------------------

File "../../../anaconda3/lib/python3.6/site-packages/hausdorff/hausdorff.py", line 14

This error may have been caused by the following argument(s):
- argument 2: cannot determine Numba type of <class 'numba.targets.registry.CPUDispatcher'>
```

**Comment by mavillan** [comment]
Hi! Please provide more context about the code that triggered this error. When you call 

`dist = hausdorff_distance(frame[0], current[0], distance="euclidean")`

what are `frame[0]` and `current[0]`?

**Comment by tomitrescak** [comment]
Sorry for not responding, used own implementation in the end. Thanks for the fix though!
